import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProviders from "@/components/ClientProviders";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientProviders>
          <header className="flex items-center justify-between border-b px-4 py-2 text-sm">
            <Link href="/" className="font-semibold">
              Today Dashboard
            </Link>
            <div className="flex items-center gap-2">
              <Link
                className="rounded border px-2 py-1"
                href="/api/auth/signin"
              >
                Sign in
              </Link>
              <Link
                className="rounded border px-2 py-1"
                href="/api/auth/signout"
              >
                Sign out
              </Link>
            </div>
          </header>
          {children}
        </ClientProviders>
      </body>
    </html>
  );
}
