import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProviders from "@/components/ClientProviders";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientProviders>
          <header className="flex items-center justify-between border-b px-4 py-2 text-sm">
            <Link href="/" className="font-semibold">
              Today Dashboard
            </Link>
            <div className="flex items-center gap-2">
              <Link className="rounded border px-2 py-1" href="/sign-in">
                Sign in
              </Link>
              {/* Client sign-out button to avoid 405 on GET */}
              {/* @ts-expect-error Async Server Component wrapper */}
              {(() => {
                const SignOutButton =
                  require("@/components/SignOutButton").default;
                return <SignOutButton />;
              })()}
            </div>
          </header>
          {children}
        </ClientProviders>
      </body>
    </html>
  );
}
